apiVersion: apps/v1
kind: Deployment
metadata:
  name: CDSWeatherForecast-app-deployment  # Name of the deployment
spec:
  replicas: 2  # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: CDSWeatherForecast-app  # Label selector to match pods controlled by this deployment
  template:
    metadata:
      labels:
        app: CDSWeatherForecast-app  # Labels applied to pods created by this deployment
    spec:
      containers:
        - name: CDSWeatherForecast-web-api-container  # Name of the container
          image: CDSWeatherForecast-web-api:latest  # Docker image to use
          imagePullPolicy: Never
          ports:
            - containerPort: 80  # Port to expose within the pod